image: node:latest

stages:
  - test
  - build

cache:
  paths:
    - node_modules

before_script:
  - yarn

jest:
  stage: test
  script:
    - yarn test

transpile:
  stage: build
  script: 
    - yarn build
