image: node:latest

cache:
  paths:
  - node_modules

stages:
  - test
  - build
  
before_script:
  - yarn install

test:
  stage: test
  script: 
    - yarn test

build:
  stage: build
  script:
    - yarn build